<?php

declare(strict_types=1);
/**
 * This file is part of SmartAdmin.
 *
 * @contact Anyon <zoujingli@qq.com>
 * @license https://github.com/zoujingli/SmartAdmin/blob/master/LICENSE
 * @document https://zoujingli.github.io/SmartAdmin
 */

namespace Library\Command;

use Hyperf\Command\Annotation\Command;
use Hyperf\Command\Command as HyperfCommand;
use Hyperf\Di\Annotation\Inject;
use Library\Service\ReleaseDatabaseService;
use Library\Support\FrontendPublisher;
use Symfony\Component\Console\Input\InputOption;

/**
 * 发布包一键安装命令。
 *
 * 正式 Phar/SFX 环境不暴露 migrate，首次部署与发布升级通过 Phar 内 release 安装包恢复数据库，
 * 随后发布 Phar 内前端资源到运行目录 public，使解压后的二进制目录可直接启动使用。
 */
#[Command(name: 'xadmin:release:install', description: 'Install release database package and publish frontend assets')]
final class ReleaseInstall extends HyperfCommand
{
    #[Inject]
    protected ReleaseDatabaseService $service;

    public function configure(): void
    {
        $this->setDescription('Install release database package and publish frontend assets')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Preview install package restore and frontend publish without writing')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Allow destructive schema SQL generated by DBAL')
            ->addOption('json', null, InputOption::VALUE_NONE, 'Emit report as JSON');
    }

    public function handle(): void
    {
        $dryRun = (bool)$this->input->getOption('dry-run');
        $force = (bool)$this->input->getOption('force');

        $database = $this->service->restore(true, false, $force, $dryRun);
        $frontendFiles = FrontendPublisher::publish($dryRun);

        $report = [
            'dry_run' => $dryRun,
            'force' => $force,
            'database' => $database,
            'frontend' => [
                'public_path' => runpath('public'),
                'files' => $frontendFiles,
                'ready' => $dryRun ? null : FrontendPublisher::publicReady(),
            ],
        ];

        if ((bool)$this->input->getOption('json')) {
            $this->line(json_encode($report, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
            return;
        }

        $this->renderReport($report);
    }

    /**
     * @param array<string,mixed> $report
     */
    private function renderReport(array $report): void
    {
        $database = is_array($report['database'] ?? null) ? $report['database'] : [];
        $frontend = is_array($report['frontend'] ?? null) ? $report['frontend'] : [];

        $this->line(($report['dry_run'] ? '[dry-run] ' : '') . 'Release install complete');
        $this->line('Force destructive SQL: ' . ($report['force'] ? 'yes' : 'no'));
        $this->line('Schema: ' . ($database['schema_path'] ?? ''));
        $this->line('Data: ' . ($database['data_path'] ?? ''));
        $this->line('Safe SQL: ' . count((array)($database['safe_sql'] ?? [])));
        $this->line('Destructive SQL: ' . count((array)($database['destructive_sql'] ?? [])));

        if (!$report['dry_run']) {
            $this->line('Executed SQL: ' . count((array)($database['executed_sql'] ?? [])));
            $this->line('Restored release data rows: ' . (int)($database['data_rows'] ?? 0));
            $this->line('Frontend files: ' . (int)($frontend['files'] ?? 0));
            $this->line('Public ready: ' . (!empty($frontend['ready']) ? 'yes' : 'no'));
        } else {
            $this->line('Frontend files: ' . (int)($frontend['files'] ?? 0));
        }
    }
}
