<?php

declare(strict_types=1);
/**
 * This file is part of SmartAdmin.
 *
 * @contact Anyon <zoujingli@qq.com>
 * @license https://github.com/zoujingli/SmartAdmin/blob/master/LICENSE
 * @document https://zoujingli.github.io/SmartAdmin
 */

namespace Library\Command;

use Hyperf\Command\Annotation\Command;
use Hyperf\Command\Command as HyperfCommand;
use Hyperf\Di\Annotation\Inject;
use Library\Service\ReleaseDatabaseService;
use Symfony\Component\Console\Input\InputOption;

#[Command(name: 'xadmin:release:restore', description: 'Restore release install package or latest runtime backup')]
final class ReleaseRestore extends HyperfCommand
{
    #[Inject]
    protected ReleaseDatabaseService $service;

    public function configure(): void
    {
        $this->setDescription('Restore release install package or latest runtime backup')
            ->addOption('install', null, InputOption::VALUE_NONE, 'Restore install package from storage/extra/release')
            ->addOption('with-data', null, InputOption::VALUE_NONE, 'Restore all table data from latest runtime backup; not allowed with --install')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Allow destructive schema SQL generated by DBAL')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Preview restore without writing to database')
            ->addOption('json', null, InputOption::VALUE_NONE, 'Emit report as JSON');
    }

    public function handle(): void
    {
        $report = $this->service->restore(
            (bool)$this->input->getOption('install'),
            (bool)$this->input->getOption('with-data'),
            (bool)$this->input->getOption('force'),
            (bool)$this->input->getOption('dry-run')
        );

        if ((bool)$this->input->getOption('json')) {
            $this->line(json_encode($report, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
            return;
        }

        $this->line(($report['dry_run'] ? '[dry-run] ' : '') . ($report['install'] ? 'Release install restore complete' : 'Release backup restore complete'));
        $this->line('Mode: ' . ($report['install'] ? 'install' : 'backup'));
        $this->line('With data: ' . ($report['with_data'] ? 'yes' : 'no'));
        $this->line('Force destructive SQL: ' . ($report['force'] ? 'yes' : 'no'));
        $this->line('Path: ' . $report['backup_path']);
        $this->line('Schema: ' . $report['schema_path']);
        $this->line('Data: ' . $report['data_path']);
        $this->line('Safe SQL: ' . count($report['safe_sql']));
        $this->line('Destructive SQL: ' . count($report['destructive_sql']));
        $this->line('Pre-upgrade backup required: ' . (!empty($report['backup_required']) ? 'yes' : 'no'));
        $preview = (array)($report['data_repair_preview'] ?? []);
        $this->line('Data repairs ready: ' . (!empty($preview['ready']) ? 'yes' : 'no'));
        $this->line('Data repairs planned: ' . count((array)($preview['items'] ?? [])));
        if (!$report['dry_run']) {
            $this->line('Executed SQL: ' . count($report['executed_sql']));
            $this->line('Restored data rows: ' . $report['data_rows']);
            $backup = (array)($report['pre_upgrade_backup'] ?? []);
            $this->line('Pre-upgrade backup: ' . (string)($backup['backup_path'] ?? 'not required'));
            $this->line('Applied data repairs: ' . count((array)($report['data_repairs']['items'] ?? [])));
        }
        if ($report['skipped_tables'] !== []) {
            $this->warn('Skipped tables: ' . implode(', ', $report['skipped_tables']));
        }
    }
}
