<?php

declare(strict_types=1);
/**
 * This file is part of SmartAdmin.
 *
 * @contact Anyon <zoujingli@qq.com>
 * @license https://github.com/zoujingli/SmartAdmin/blob/master/LICENSE
 * @document https://github.com/zoujingli/SmartAdmin/blob/master/readme.md
 */

namespace Library\Command;

use Hyperf\Command\Annotation\Command;
use Hyperf\Command\Command as HyperfCommand;
use Hyperf\Di\Annotation\Inject;
use Library\Service\ReleaseDatabaseService;
use Symfony\Component\Console\Input\InputOption;

#[Command(name: 'xadmin:release:upgrade', description: 'Upgrade database structure and release-managed data from release snapshots')]
final class ReleaseUpgrade extends HyperfCommand
{
    #[Inject]
    protected ReleaseDatabaseService $service;

    public function configure(): void
    {
        $this->setDescription('Upgrade database structure and release-managed data from release snapshots')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Show SQL and data plan without writing to database')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Allow destructive schema SQL generated by DBAL')
            ->addOption('json', null, InputOption::VALUE_NONE, 'Emit report as JSON');
    }

    public function handle(): void
    {
        $report = $this->service->upgrade(
            (bool)$this->input->getOption('force'),
            (bool)$this->input->getOption('dry-run')
        );

        if ((bool)$this->input->getOption('json')) {
            $this->line(json_encode($report, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
            return;
        }

        $this->line(($report['dry_run'] ? '[dry-run] ' : '') . 'Release database upgrade plan');
        $this->line('Force destructive SQL: ' . ($report['force'] ? 'yes' : 'no'));
        $this->line('Runtime backup: ' . $report['runtime_backup_path']);
        $this->line('Backup tables: ' . implode(', ', $report['backup_tables']));
        $this->line('Ignore tables: ' . implode(', ', $report['ignore_tables']));
        $this->line('Safe SQL: ' . count($report['safe_sql']));
        foreach ($report['safe_sql'] as $sql) {
            $this->line('  [safe] ' . $sql);
        }
        $this->line('Destructive SQL: ' . count($report['destructive_sql']));
        foreach ($report['destructive_sql'] as $sql) {
            $this->line('  [destructive] ' . $sql);
        }
        if (!$report['force'] && $report['destructive_sql'] !== []) {
            $this->warn('Destructive SQL was skipped. Re-run with --force to execute it.');
        }
        if (!$report['dry_run']) {
            $this->line('Executed SQL: ' . count($report['executed_sql']));
            $this->line('Runtime backup rows: ' . $report['runtime_backup_rows']);
            $this->line('Restored release data rows: ' . $report['data_rows']);
        }
        if ($report['skipped_tables'] !== []) {
            $this->warn('Skipped tables: ' . implode(', ', $report['skipped_tables']));
        }
    }
}
